### ISSUE TITLE
Possible sans la touche "fn" ?

### ISSUE THREAD

**Issue by starckio** [jlj/NativeDisplayBrightness#2]
J'arrive de l'article du JournalduLapin,
Le premier développement fonctionne déjà très bien mais je préfère le votre pour le multiples écran.
Je dispose d'un clavier Apple et j'aimerai si possible ne pas passer par la touche "fn".

Salutations et merci.

**Comment by Anywhere-Music-Player** [comment]
Nein :D 
I know English only.

**Comment by jlj** [comment]
[*see English version below*]
Malheureusement les touches de luminosité, volume, … des claviers Apple ne sont pas accessible aux applications, ni aux handlers de touches spécifiques. C'est pour cela qu'on est obligé de passer par la touche "fn", afin de rendre les appuis touches de luminosité visibles depuis l'application.
Donc pas possible d'utiliser directement les touches de luminosité.

----

Unfortunately, brightness, volume… keys on Apple keyboards are not accessible from applications nor from custom key-handlers. That's why utilities like NativeDisplayBrightness have to use the "fn" key to handle keypresses on brightness keys.
Therefore direct use of the bigness key -without the "fn" key- is not possible here.
